// <auto-generated />
using System;
using MagicVilla_API.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231222220409_AgregarNumeroVillaTabla")]
    partial class AgregarNumeroVillaTabla
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_API.Modelos.NumeroVilla", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<string>("DetalleEspecial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualización")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreación")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("NumeroVillas");
                });

            modelBuilder.Entity("MagicVilla_API.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MetrosCuadrados")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenidad = "Amenidad 1",
                            Detalle = "Villa 1",
                            FechaActualizacion = new DateTime(2023, 12, 22, 17, 4, 8, 854, DateTimeKind.Local).AddTicks(5975),
                            FechaCreacion = new DateTime(2023, 12, 22, 17, 4, 8, 854, DateTimeKind.Local).AddTicks(5961),
                            ImagenUrl = "",
                            MetrosCuadrados = 100.0,
                            Nombre = "Villa 1",
                            Ocupantes = 4,
                            Tarifa = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Amenidad = "Amenidad 2",
                            Detalle = "Villa 2",
                            FechaActualizacion = new DateTime(2023, 12, 22, 17, 4, 8, 854, DateTimeKind.Local).AddTicks(5976),
                            FechaCreacion = new DateTime(2023, 12, 22, 17, 4, 8, 854, DateTimeKind.Local).AddTicks(5976),
                            ImagenUrl = "",
                            MetrosCuadrados = 150.0,
                            Nombre = "Villa 2",
                            Ocupantes = 6,
                            Tarifa = 150.0
                        },
                        new
                        {
                            Id = 3,
                            Amenidad = "Amenidad 3",
                            Detalle = "Villa 3",
                            FechaActualizacion = new DateTime(2023, 12, 22, 17, 4, 8, 854, DateTimeKind.Local).AddTicks(5978),
                            FechaCreacion = new DateTime(2023, 12, 22, 17, 4, 8, 854, DateTimeKind.Local).AddTicks(5977),
                            ImagenUrl = "",
                            MetrosCuadrados = 200.0,
                            Nombre = "Villa 3",
                            Ocupantes = 8,
                            Tarifa = 200.0
                        });
                });

            modelBuilder.Entity("MagicVilla_API.Modelos.NumeroVilla", b =>
                {
                    b.HasOne("MagicVilla_API.Modelos.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
